#!/usr/bin/env python3

# TODO
import sys
import helpers

from analyzer import Analyzer
from termcolor import colored

def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets screen_name")

    # instantiate analyzer
    analyzer = Analyzer()
    # analyze word
    screen_name = sys.argv[1]
    tweetsPack = helpers.get_user_timeline(screen_name, 50)
    for tweet in tweetsPack:
        score = analyzer.analyze(tweet)
        if score > 0.0:
            print(colored(score, "green"), colored(tweet, "green"))
        elif score < 0.0:
            print(colored(score, "red"), colored(tweet, "red"))
        else:
            print(colored(score, "yellow"), colored(tweet, "yellow"))

if __name__ == "__main__":
    main()